import Head from "next/head";
import { motion } from "framer-motion";
import { TagCloud, TagCloudOptions } from "@frank-mayer/react-tag-cloud";
import useDarkTheme from "../store/useDarkTheme.store";

function About() {
  const { darkTheme } = useDarkTheme((state) => state);

  const generateTagCloudRadius = (windowWidth: number) => {
    if (windowWidth < 500) {
      return 150;
    } else if (windowWidth >= 500 && windowWidth < 900) {
      return 200;
    } else {
      return 250;
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main
        initial={{ y: "100%", opacity: 0 }}
        animate={{ y: "0%", opacity: 1 }}
        transition={{ duration: 0.75, ease: "easeOut" }}
        exit={{ y: "-100%", opacity: 0 }}
        className="max-w-7xl mx-auto min-h-screen px-6 py-7"
      >
        <div className="mt-20">
          <h1 className="transition duration-1000 text-red-500 text-3xl dark:text-amber-500">
            About
          </h1>
        </div>

        <TagCloud
          options={(w: Window & typeof globalThis): TagCloudOptions => ({
            // radius: Math.min(500, w.innerWidth, w.innerHeight) / 2,
            radius: generateTagCloudRadius(w.innerWidth),
            maxSpeed: "normal",
            containerClass: "m-auto",
            itemClass: darkTheme
              ? "text-white text-xs md:text-base hover:text-amber-500"
              : "text-black text-xs md:text-base hover:text-red-500",
          })}
          onClickOptions={{ passive: true }}
        >
          {[
            "ReactJS",
            "TypeScript",
            "NextJS",
            "JavaScript",
            "Git",
            "DynamoDB",
            "HTML",
            "Framer Motion",
            "CSS",
            "SASS",
            "Postman",
            "VSCode",
            "AWS Lambda",
            "NodeJS",
            "Axios",
            "React Query",
            "Zustand",
            "Recharts",
            "Zod",
            "TailwindCSS",
          ]}
        </TagCloud>
      </motion.main>
    </>
  );
}

export default About;
