import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-7xl mx-auto">
        <h1 className="transition duration-1000 text-red-500 text-3xl dark:text-amber-500">
          Hello Antony
        </h1>
      </main>
    </>
  );
}
